# Site settings
title: Cancer Vaccine Institute
email: webmaster@cancervaccine.org.uk
description: > # this means to ignore newlines until "baseurl:"
  The Cancer Vaccine Institute (CVI) funds research into the use of vaccines and
  immunotherapy for the treatment of cancer. Our vision is that cancer vaccines
  will become a standard treatment and improve survival rates and patients’
  quality of life for a wide range of cancers.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.cancervaccine.org.uk/" # the base hostname & protocol for your site
twitter_username: thecvinstitute
telephone: 0845 6020662
hero-image-class: default-hero-image

# Build settings
markdown: kramdown

# Pretty URL
permalink: "news/:title"

# Custom categories
categories: [navbar]

sass:
    style: :compressed

collections:
  research-projects:
    output: true
    permalink: /:collection/:path/
  case-studies:
    output: true
    permalink: /:collection/:path/
  tribute-funds:
    output: true
    permalink: /:collection/:path/
